/**This Utility class is created for adding fixed value **/
public class ChildCaseUtil {
     public static String  OBJ_TYPE='Case';
     public static String  REC_TYP_NM_CHG='Name_Change_Request';
     public static String  REC_TYP_NPI_ID='NPI_Tax_Id_Change';
     public static String  REC_TYP_PHY_ADD_CHG='Physical_Address_Change';
     public static String  REC_TYP_BILL_ADD_CHG='Billing_Address_Change';
     public static String  REC_TYP_CRED_CHG='Credentialing_Change';
     public static String  REC_TYP_ADMIN_CHG='Administrative_Change';   
}