



 function addNetworkObjectData()
 {
         
	this.row = 
		{
			
			
			"dataElement1": 
			{
				"label":  "Effective Date",
				"inputType": "date",				
				"required": false,
				"id": "ncEffectiveDate", 
				"class": ""
			},
			"dataElement2": 
			{
				"label":  "Comment",
				"inputType": "textarea",				
				"required": false,
				"id": "comments", 
				"class": "",
				"placeholder": "Enter your comments",
				"cols": "25",
				"rows": "2"
			}	
												
		}
					
		
	
	
 }

